using System;

namespace Click_To_Website
{
    public partial class Materialize_Setup 
    {
        String[] MDI_Text_Only =
{
"<!doctype html>",
"<!--",
"  Material Design Lite",
"  Copyright 2015 Google Inc. All rights reserved.",
"",
"  Licensed under the Apache License, Version 2.0 (the \"License\");",
"  you may not use this file except in compliance with the License.",
"  You may obtain a copy of the License at",
"",
"       https://www.apache.org/licenses/LICENSE-2.0",
"",
"  Unless required by applicable law or agreed to in writing, software",
"  distributed under the License is distributed on an \"AS IS\" BASIS,",
"  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
"  See the License for the specific language governing permissions and",
"  limitations under the License",
"-->",
"<html lang=\"en\">",
"  <head>",
"    <meta charset=\"utf-8\">",
"    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">",
"    <meta name=\"description\" content="+"<ADDDescription>"+">", //Add Description
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0\">",
"    <title>"+"<ADDTitle>"+"</title>", //ADD Title
"",
"    <!-- Add to homescreen for Chrome on Android -->",
"    <meta name=\"mobile-web-app-capable\" content=\"yes\">",
"    <link rel=\"icon\" sizes=\"192x192\" href=\"images/android-desktop.png\">",
"",
"    <!-- Add to homescreen for Safari on iOS -->",
"    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">",
"    <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">",
"    <meta name=\"apple-mobile-web-app-title\" content=\""+"<ADDTitle>"+"\">",
"    <link rel=\"apple-touch-icon-precomposed\" href=\"images/ios-desktop.png\">",
"",
"   <!-- Tile icon for Win8 (144x144 + tile color) -->",
"    <meta name=\"msapplication-TileImage\" content=\"images/touch/ms-touch-icon-144x144-precomposed.png\">",
"    <meta name=\"msapplication-TileColor\" content=\""+"<ADDTileColour>"+"\">",
"",
"    <link rel=\"shortcut icon\" href=\"images/favicon.png\">",
"",
"    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->",
"    <!--",
"    <link rel=\"canonical\" href=\"http://www.example.com/\">",
"    -->",
"",
"    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en\">",
"    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">",
"    <link rel=\"stylesheet\" href=\"https://code.getmdl.io/1.3.0/material.deep_purple-pink.min.css\">",
"    <link rel=\"stylesheet\" href=\"styles.css\">",
"    <style>",
"    #view-source {",
"      position: fixed;",
"      display: block;",
"      right: 0;",
"      bottom: 0;",
"      margin-right: 40px;",
"      margin-bottom: 40px;",
"      z-index: 900;",
"    }",
//This lets me change the colour of the top and nav bar
"	.mdl-color--primary-dark",
"    {",
//Top
"    background-color: rgb("+"<ADDR-30>"+","+"<ADDG-30>"+","+"<ADDB-30>"+") !important;",
"    }",
"	.mdl-color--primary",
"    {",
//Bar
"      background-color: rgb("+"<ADDR>"+","+"<ADDG>"+","+"<ADDB>"+") !important;",
"    }",
//This lets me change the colour of the top and nav bar
"    </style>",
"      </head>",
"  <body class=\"mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base\">",
"    <div class=\"mdl-layout mdl-js-layout mdl-layout--fixed-header\">",
"      <header class=\"mdl-layout__header mdl-layout__header--scroll mdl-color--primary\">",
"        <div class=\"mdl-layout--large-screen-only mdl-layout__header-row\">",
"        </div>",
"       <div class=\"mdl-layout--large-screen-only mdl-layout__header-row\">",
"          <h3>"+"<ADDTitle>"+"</h3>",
"        </div>",
"        <div class=\"mdl-layout--large-screen-only mdl-layout__header-row\">",
"        </div>",
"        <div class=\"mdl-layout__tab-bar mdl-js-ripple-effect mdl-color--primary-dark\">",
"        <ADDWebsiteNav>", //Website Nav
"          <button class=\"mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored mdl-shadow--4dp mdl-color--accent\" id=\"add\">",
"            <i class=\"material-icons\" role=\"presentation\">add</i>",
"            <span class=\"visuallyhidden\">Add</span>",
"         </button>",
"    </div>",
"    </header>",
"      <main class=\"mdl-layout__content\">",
"<ADDWebpage>",
"<ADDDefaultPage>",
"        <footer class=\"mdl-mega-footer\">",
"          <div class=\"mdl-mega-footer--middle-section\">",
"            <div class=\"mdl-mega-footer--drop-down-section\">",
"              <input class=\"mdl-mega-footer--heading-checkbox\" type=\"checkbox\" checked>",
"              <h1 class=\"mdl-mega-footer--heading\">Features</h1>",
"          <ul class=\"mdl-mega-footer--link-list\">",
"            <li><a href=\"#\">About</a></li>",
"            <li><a href=\"#\">Terms</a></li>",
"            <li><a href=\"#\">Partners</a></li>",
"            <li><a href=\"#\">Updates</a></li>",
"          </ul>",
"        </div>",
"        <div class=\"mdl-mega-footer--drop-down-section\">",
"          <input class=\"mdl-mega-footer--heading-checkbox\" type=\"checkbox\" checked>",
"          <h6 class=\"mdl-mega-footer--heading\">Details</h6>",
"          <ul class=\"mdl-mega-footer--link-list\">",
"            <li><a href=\"#\">Spec</a></li>",
"            <li><a href=\"#\">Tools</a></li>",
"            <li><a href=\"#\"> Resources</a></li>",
"          </ul>",
"        </div>",
"        <div class=\"mdl-mega-footer--drop-down-section\">",
"          <input class=\"mdl-mega-footer--heading-checkbox\" type=\"checkbox\" checked>",
"          <h6 class=\"mdl-mega-footer--heading\">Technology</h6>",
"          <ul class=\"mdl-mega-footer--link-list\">",
"            <li><a href=\"#\">How it works</a></li>",
"            <li><a href=\"#\">Patterns</a></li>",
"                <li><a href=\"#\">Usage</a></li>",
"                <li><a href=\"#\">Products</a></li>",
"                <li><a href=\"#\">Contracts</a></li>",
"              </ul>",
"            </div>",
"            <div class=\"mdl-mega-footer--drop-down-section\">",
"          <input class=\"mdl-mega-footer--heading-checkbox\" type=\"checkbox\" checked>",
"          <h6 class=\"mdl-mega-footer--heading\">FAQ</h6>",
"          <ul class=\"mdl-mega-footer--link-list\">",
"            <li><a href=\"#\">Questions</a></li>",
"            <li><a href=\"#\">Answers</a></li>",
"            <li><a href=\"#\">Contact us</a></li>",
"          </ul>",
"        </div>",
"      </div>",
"          <div class=\"mdl-mega-footer--bottom-section\">",
"            <div class=\"mdl-logo\">",
"              More Information",
"            </div>",
"            <ul class=\"mdl-mega-footer--link-list\">",
"              <li><a href=\"https://developers.google.com/web/starter-kit/ \">Web Starter Kit</a></li>",
"              <li><a href=\"https://github.com/google/material-design-lite/blob/mdl-1.x/templates/text-only/ \">View Source Code</a></li>",
"              <li><a href=\"#\">Help</a></li>",
"              <li><a href=\"#\">Privacy and Terms</a></li>",
"            </ul>",
"          </div>",
"        </footer>",
"      </main>",
"    </div>",
"    <script src=\"https://code.getmdl.io/1.3.0/material.min.js \"></script>",
"      </body>",
"    </html>",
};

        string[] DefaultPage = {
"        <div class=\"mdl-layout__tab-panel is-active\" id=\"default_page\">",
"          <section class=\"section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp\">",
"            <header class=\"section__play-btn mdl-cell mdl-cell--3-col-desktop mdl-cell--2-col-tablet mdl-cell--4-col-phone mdl-color--teal-100 mdl-color-text--white\">",
"              <i class=\"material-icons\">play_circle_filled</i>",
"                </header>",
"                <div class=\"mdl-card mdl-cell mdl-cell--9-col-desktop mdl-cell--6-col-tablet mdl-cell--4-col-phone\">",
"                  <div class=\"mdl-card-supporting-text\">",
"                    <h4>Features</h4>",
"                Dolore ex deserunt aute fugiat aute nulla ea sunt aliqua nisi cupidatat eu. Nostrud in laboris labore nisi amet do dolor eu fugiat consectetur elit cillum esse.",
"             </div>",
"              <div class=\"mdl-card__actions\">",
"                <a href = \"#\" class=\"mdl-button\">Read our features</a>",
"              </div>",
"            </div>",
"            <button class=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\" id=\"btn1\">",
"              <i class=\"material-icons\">more_vert</i>",
"            </button>",
"            <ul class=\"mdl-menu mdl-js-menu mdl-menu--bottom-right\" for=\"btn1\">",
"              <li class=\"mdl-menu__item\">Lorem</li>",
"              <li class=\"mdl-menu__item\" disabled>Ipsum</li>",
"              <li class=\"mdl-menu__item\">Dolor</li>",
"            </ul>",
"          </section>",
"          <section class=\"section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp\">",
"            <div class=\"mdl-card mdl-cell mdl-cell--12-col\">",
"              <div class=\"mdl-card__supporting-text mdl-grid mdl-grid--no-spacing\">",
"                <h4 class=\"mdl-cell mdl-cell--12-col\">Details</h4>",
"                <div class=\"section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone\">",
"                  <div class=\"section__circle-container__circle mdl-color--primary\"></div>",
"                </div>",
"                <div class=\"section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone\">",
"                  <h5>Lorem ipsum dolor sit amet</h5>",
"                  Dolore ex deserunt aute fugiat aute nulla ea sunt aliqua nisi cupidatat eu.Duis nulla tempor do aute et eiusmod velit exercitation nostrud quis<a href=\"#\">proident minim</a>.",
"                </div>",
"                <div class=\"section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone\">",
"                  <div class=\"section__circle-container__circle mdl-color--primary\"></div>",
"                </div>",
"                <div class=\"section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone\">",
"                  <h5>Lorem ipsum dolor sit amet</h5>",
"                  Dolore ex deserunt aute fugiat aute nulla ea sunt aliqua nisi cupidatat eu.Duis nulla tempor do aute et eiusmod velit exercitation nostrud quis<a href=\"#\">proident minim</a>.",
"                </div>",
"                <div class=\"section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone\">",
"                  <div class=\"section__circle-container__circle mdl-color--primary\"></div>",
"                </div>",
"                <div class=\"section__text mdl-cell mdl-cell--10-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone\">",
"                 <h5>Lorem ipsum dolor sit amet</h5>",
"                  Dolore ex deserunt aute fugiat aute nulla ea sunt aliqua nisi cupidatat eu.Duis nulla tempor do aute et eiusmod velit exercitation nostrud quis<a href=\"#\"> proident minim</a>.",
"                </div>",
"             </div>",
"              <div class=\"mdl-card__actions\">",
"                <a href=\"#\" class=\"mdl-button\">Read our features</a>",
"              </div>",
"            </div>",
"            <button class=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\" id=\"btn2\">",
"              <i class=\"material-icons\">more_vert</i>",
"            </button>",
"            <ul class=\"mdl-menu mdl-js-menu mdl-menu--bottom-right\" for=\"btn2\">",
"              <li class=\"mdl-menu__item\">Lorem</li>",
"              <li class=\"mdl-menu__item\" disabled>Ipsum</li>",
"              <li class=\"mdl-menu__item\">Dolor</li>",
"            </ul>",
"          </section>",
"          <section class=\"section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp\">",
"            <div class=\"mdl-card mdl-cell mdl-cell--12-col\">",
"              <div class=\"mdl-card__supporting-text\">",
"                <h4>Technology</h4>",
"                Dolore ex deserunt aute fugiat aute nulla ea sunt aliqua nisi cupidatat eu.Nostrud in laboris labore nisi amet do dolor eu fugiat consectetur elit cillum esse.Pariatur occaecat nisi laboris tempor laboris eiusmod qui id Lorem esse commodo in. Exercitation aute dolore deserunt culpa consequat elit labore incididunt elit anim.",
"              </div>",
"              <div class=\"mdl-card__actions\">",
"                <a href=\"#\" class=\"mdl-button\">Read our features</a>",
"              </div>",
"            </div>",
"            <button class=\"mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon\" id=\"btn3\">",
"              <i class=\"material-icons\">more_vert</i>",
"            </button>",
"            <ul class=\"mdl-menu mdl-js-menu mdl-menu--bottom-right\" for=\"btn3\">",
"              <li class=\"mdl-menu__item\">Lorem</li>",
"              <li class=\"mdl-menu__item\" disabled>Ipsum</li>",
"              <li class=\"mdl-menu__item\">Dolor</li>",
"            </ul>",
"          </section>",
"          <section class=\"section--footer mdl-color--white mdl-grid\">",
"            <div class=\"section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone\">",
"              <div class=\"section__circle-container__circle mdl-color--accent section__circle--big\"></div>",
"            </div>",
"            <div class=\"section__text mdl-cell mdl-cell--4-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone\">",
"              <h5>Lorem ipsum dolor sit amet</h5>",
"              Qui sint ut et qui nisi cupidatat.Reprehenderit nostrud proident officia exercitation anim et pariatur ex.",
"            </div>",
"            <div class=\"section__circle-container mdl-cell mdl-cell--2-col mdl-cell--1-col-phone\">",
"              <div class=\"section__circle-container__circle mdl-color--accent section__circle--big\"></div>",
"            </div>",
"            <div class=\"section__text mdl-cell mdl-cell--4-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone\">",
"              <h5>Lorem ipsum dolor sit amet</h5>",
"              Qui sint ut et qui nisi cupidatat.Reprehenderit nostrud proident officia exercitation anim et pariatur ex.",
"            </div>",
"          </section>",
"        </div>",
};

        String[] MDI_Text_Only_CSS =
    {
"/**",
"* Copyright 2015 Google Inc. All Rights Reserved.",
"*",
"* Licensed under the Apache License, Version 2.0 (the \"License\");",
"* you may not use this file except in compliance with the License.",
"* You may obtain a copy of the License at",
"*",
"*      http://www.apache.org/licenses/LICENSE-2.0",
"*",
"* Unless required by applicable law or agreed to in writing, software",
"* distributed under the License is distributed on an \"AS IS\" BASIS,",
"* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
"* See the License for the specific language governing permissions and",
"* limitations under the License.",
"*/",
"",
"html, body {",
"  font-family: 'Roboto', 'Helvetica', sans-serif;",
"  margin: 0;",
"  padding: 0;",
"}",
".mdl-demo .mdl-layout__header-row {",
"  padding-left: 40px;",
"}",
".mdl-demo .mdl-layout.is-small-screen .mdl-layout__header-row h3 {",
"  font-size: inherit;",
"}",
".mdl-demo .mdl-layout__tab-bar-button {",
"  display: none;",
"}",
".mdl-demo .mdl-layout.is-small-screen .mdl-layout__tab-bar .mdl-button {",
"  display: none;",
"}",
".mdl-demo .mdl-layout:not(.is-small-screen) .mdl-layout__tab-bar,",
".mdl-demo .mdl-layout:not(.is-small-screen) .mdl-layout__tab-bar-container {",
"  overflow: visible;",
"}",
".mdl-demo .mdl-layout__tab-bar-container {",
"  height: 64px;",
"}",
".mdl-demo .mdl-layout__tab-bar {",
"  padding: 0;",
"  padding-left: 16px;",
"  box-sizing: border-box;",
"  height: 100%;",
"  width: 100%;",
"}",
".mdl-demo .mdl-layout__tab-bar .mdl-layout__tab {",
"  height: 64px;",
"  line-height: 64px;",
"}",
".mdl-demo .mdl-layout__tab-bar .mdl-layout__tab.is-active::after {",
"  background-color: white;",
"  height: 4px;",
"}",
".mdl-demo main > .mdl-layout__tab-panel {",
"  padding: 8px;",
"  padding-top: 48px;",
"}",
".mdl-demo .mdl-card {",
"  height: auto;",
"  display: -webkit-flex;",
"  display: -ms-flexbox;",
"  display: flex;",
"  -webkit-flex-direction: column;",
"  -ms-flex-direction: column;",
"  flex-direction: column;",
"}",
".mdl-demo .mdl-card > * {",
"  height: auto;",
"}",
".mdl-demo .mdl-card .mdl-card__supporting-text {",
"  margin: 40px;",
"  -webkit-flex-grow: 1;",
"  -ms-flex-positive: 1;",
"  flex-grow: 1;",
"  padding: 0;",
"  color: inherit;",
"  width: calc(100% - 80px);",
"}",
".mdl-demo.mdl-demo .mdl-card__supporting-text h4 {",
"  margin-top: 0;",
"  margin-bottom: 20px;",
"}",
".mdl-demo .mdl-card__actions {",
"  margin: 0;",
"  padding: 4px 40px;",
"  color: inherit;",
"}",
".mdl-demo .mdl-card__actions a {",
"  color: #00BCD4;",
"  margin: 0;",
"}",
".mdl-demo .mdl-card__actions a:hover,",
".mdl-demo .mdl-card__actions a:active {",
"  color: inherit;",
"  background-color: transparent;",
"}",
".mdl-demo .mdl-card__supporting-text + .mdl-card__actions {",
"  border-top: 1px solid rgba(0, 0, 0, 0.12);",
"}",
".mdl-demo #add {",
"  position: absolute;",
"  right: 40px;",
"  top: 36px;",
"  z-index: 999;",
"}",
"",
".mdl-demo .mdl-layout__content section:not(:last-of-type) {",
"  position: relative;",
"  margin-bottom: 48px;",
"}",
".mdl-demo section.section--center {",
"  max-width: 860px;",
"}",
".mdl-demo #features section.section--center {",
"  max-width: 620px;",
"}",
".mdl-demo section > header{",
"  display: -webkit-flex;",
"  display: -ms-flexbox;",
"  display: flex;",
"  -webkit-align-items: center;",
"  -ms-flex-align: center;",
"  align-items: center;",
"  -webkit-justify-content: center;",
"  -ms-flex-pack: center;",
"  justify-content: center;",
"}",
".mdl-demo section > .section__play-btn {",
"  min-height: 200px;",
"}",
".mdl-demo section > header > .material-icons {",
"  font-size: 3rem;",
"}",
".mdl-demo section > button {",
"  position: absolute;",
"  z-index: 99;",
"  top: 8px;",
"  right: 8px;",
"}",
".mdl-demo section .section__circle {",
"  display: -webkit-flex;",
"  display: -ms-flexbox;",
"  display: flex;",
"  -webkit-align-items: center;",
"  -ms-flex-align: center;",
"  align-items: center;",
"  -webkit-justify-content: flex-start;",
"  -ms-flex-pack: start;",
"  justify-content: flex-start;",
"  -webkit-flex-grow: 0;",
"  -ms-flex-positive: 0;",
"  flex-grow: 0;",
"  -webkit-flex-shrink: 1;",
"  -ms-flex-negative: 1;",
"  flex-shrink: 1;",
"}",
".mdl-demo section .section__text {",
"  -webkit-flex-grow: 1;",
"  -ms-flex-positive: 1;",
"  flex-grow: 1;",
"  -webkit-flex-shrink: 0;",
"  -ms-flex-negative: 0;",
"  flex-shrink: 0;",
"  padding-top: 8px;",
"}",
".mdl-demo section .section__text h5 {",
"  font-size: inherit;",
"  margin: 0;",
"  margin-bottom: 0.5em;",
"}",
".mdl-demo section .section__text a {",
"  text-decoration: none;",
"}",
".mdl-demo section .section__circle-container > .section__circle-container__circle {",
"  width: 64px;",
"  height: 64px;",
"  border-radius: 32px;",
"  margin: 8px 0;",
"}",
".mdl-demo section.section--footer .section__circle--big {",
"  width: 100px;",
"  height: 100px;",
"  border-radius: 50px;",
"  margin: 8px 32px;",
"}",
".mdl-demo .is-small-screen section.section--footer .section__circle--big {",
"  width: 50px;",
"  height: 50px;",
"  border-radius: 25px;",
"  margin: 8px 16px;",
"}",
".mdl-demo section.section--footer {",
"  padding: 64px 0;",
"  margin: 0 -8px -8px -8px;",
"}",
".mdl-demo section.section--center .section__text:not(:last-child) {",
"  border-bottom: 1px solid rgba(0,0,0,y.13);",
"}",
".mdl-demo .mdl-card .mdl-card__supporting-text > h3:first-child {",
"  margin-bottom: 24px;",
"}",
".mdl-demo .mdl-layout__tab-panel:not(#overview) {",
"  background-color: white;",
"}",
".mdl-demo #features section {",
"  margin-bottom: 72px;",
"}",
".mdl-demo #features h4, #features h5 {",
"  margin-bottom: 16px;",
"}",
".mdl-demo .toc {",
"  border-left: 4px solid #C1EEF4;",
"  margin: 24px;",
"  padding: 0;",
"  padding-left: 8px;",
"  display: -webkit-flex;",
"  display: -ms-flexbox;",
"  display: flex;",
"  -webkit-flex-direction: column;",
"  -ms-flex-direction: column;",
"  flex-direction: column;",
"}",
".mdl-demo .toc h4 {",
"  font-size: 0.9rem;",
"  margin-top: 0;",
"}",
".mdl-demo .toc a {",
"  color: #4DD0E1;",
"  text-decoration: none;",
"  font-size: 16px;",
"  line-height: 28px;",
"  display: block;",
"}",
".mdl-demo .mdl-menu__container {",
"  z-index: 99;",
"}",
};
    }
}